apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3038
    protocol: TCP
    targetPort: web
    name: http
  selector:
    app: grafana
