
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ssd
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: monitoring
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:GRAFANA_VERSION
        env:
        - name: GF_AUTH_GITHUB_ENABLED
          value: "true"
        - name: GF_AUTH_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-credentials
              key: id
        - name: GF_AUTH_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-credentials
              key: secret
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: user
        #- name: GF_AUTH_GITHUB_SCOPES
        #  value: "user:email,read:org"
        #- name: GF_AUTH_GITHUB_AUTH_URL
        #  value: "https://github.com/login/oauth/authorize"
        #- name: GF_AUTH_GITHUB_TOKEN_URL
        #  value: "https://github.com/login/oauth/access_token"
        #- name: GF_AUTH_GITHUB_API_URL
        #  value: "https://github.com/login/oauth/"
        #- name: GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS
        #  value: "LarkStreet"
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: password
        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_SMTP_HOST
          value: "email-smtp.us-west-2.amazonaws.com:587"
        - name: GF_SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-credentials
              key: username
        - name: GF_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-credentials
              key: password
        - name: GF_SMTP_FROM_ADDRESS
          value: "internal@rila.io"
        - name: GF_SMTP_FROM_NAME
          value: "RILA Internal"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/grafana-storage
        - name: grafana-persistent-storage
          mountPath: /var/lib/grafana
        ports:
        - name: web
          containerPort: 3000
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
      - name: grafana-watcher
        image: quay.io/coreos/grafana-watcher:v0.0.8
        args:
          - '--watch-dir=/var/grafana-dashboards'
          - '--grafana-url=http://localhost:3000'
        env:
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: user
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: password
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
        - name: grafana-dashboards
          mountPath: /var/grafana-dashboards
      nodeSelector:
        node_label_key: node_label_value
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-persistent-storage
        persistentVolumeClaim:
          claimName: grafana-persistent-storage
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
